language: go
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
go:
- "1.11"
- "1.12"
- "master"
install:
  - go build
script:
  - ./go-sdk-demo