language: go
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
go:
- "1.10"
- "1.11"
- "1.12"
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^dependabot.*$/
install:
  - go get -u github.com/kardianos/govendor
  - go install github.com/kardianos/govendor
  - govendor sync
script:
  - go run main.go