language: go
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
go:
- "1.13"
- "1.14"
install:
  - go get -u github.com/kardianos/govendor
  - go install github.com/kardianos/govendor
  - govendor sync
script:
  - go run main.go
