name: Release
on: 
  push:
    branches-ignore:
      - "dependabot/**"
    tags-ignore: 
      - "**"
  pull_request:
    tags-ignore: 
      - "**"

jobs:
  test:
    name: Test @ Go
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.7"
        #TODO govendor is deprecated -> go modules
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build .
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      - name: Run test
        run: go run main.go
