name: Release
on: 
  # will run for every branch, except tags. See RSRMID-206.
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "**"
    # Sequence of patterns matched against refs/tags
    tags-ignore: 
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore: 
      - "**"

jobs:
  test:
    name: Test @ Go
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.15"
          check-latest: true
        #TODO govendor is deprecated -> go modules
      - name: Run vet & lint
        run: go vet .
      - name: Run test
        run: go run main.go
