name: Test
on: 
  workflow_call:

jobs:
  test:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    name: 🧪 Testing
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.RTLDEV_MW_CI_GOLANG_VERSION }}
          check-latest: true
      - name: Run vet & lint
        run: go vet .
      - name: Run test
        run: go run main.go
